services:

  payment-database:
    image: postgres:17.4
    container_name: payment-postgres
    ports:
      - "7541:5432"
    environment:
      - POSTGRES_DB=paymentdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - backend

  payment-service:
    build: payservice/server
    image: payment
    container_name: payment
    ports:
      - "8081:8081"
    depends_on:
      payment-database:
        condition: service_healthy
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://payment-database:5432/paymentdb
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=12345
    networks:
      - backend

  intershop-database:
    image: postgres:17.4
    container_name: intershop-postgres
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=intershopdb
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=12345
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
    networks:
      - backend

  intershop-cache:
    image: redis:8.0.0
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "-a", "12345", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    tty: true
    stdin_open: true
    networks:
      - backend

  intershop-service:
    build: shop/
    image: intershop
    container_name: intershop
    ports:
      - "8080:8080"
    depends_on:
      intershop-database:
        condition: service_healthy
      intershop-cache:
        condition: service_healthy
      payment-service:
        condition: service_started
    environment:
      - SPRING_R2DBC_URL=r2dbc:postgresql://intershop-database:5432/intershopdb
      - SPRING_R2DBC_USERNAME=user
      - SPRING_R2DBC_PASSWORD=12345
      - SPRING_REDIS_HOST=intershop-cache
      - SPRING_REDIS_PORT=6379
      - PAYMENT_SERVER_URL=http://payment-service:8081
    networks:
      - backend

networks:
  backend: