spring:
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/intershop
#    username: ${username}
#    password: ${password}
    username: postgres
    password: Inushing1980
    pool:
      enabled: true                               # Включение пула соединений
      initial-size: 10                            # Начальное количество соединений в пуле
      max-size: 50                                # Максимальное количество соединений
      max-idle-time: 30s                          # Время бездействия соединения перед закрытием
      max-life-time: 10m                          # Максимальное время жизни соединения
      validation-query: SELECT 1                  # SQL-запрос для проверки работоспособности соединения
  sql:
    init.mode: always
  thymeleaf:
      encoding: UTF-8

logging:
  pattern.file: "%d{HH:mm:ss} %-5level %logger{36} - %msg%n"
  level:
    root: INFO
    org.zalando.logbook: INFO

application:
  user_id: 2  #  id текущего пользователя
  items:
    perline: 3  #  количество товаров в одном ряду
    load.enabled: true  #  включена возможность загрузки товаров через административную панель
    images.directory: c:/temp/imageStorage   #  директория для хранения загруженных картинок
